#This CI gets latest godotengine from master, patch the engine and
#export the game to various platforms before uploading it back to my site
#This allow quick and easy testing with added CI

before_script:
  - mkdir KHR2FM
  - find * -maxdepth 0 -name 'KHR2FM' -prune -o -exec cp -vr '{}' 'KHR2FM' ';'
  - find * -maxdepth 0 -name 'KHR2FM' -prune -o -exec rm -rf '{}' ';'
  - apt-get update -qq && apt-get install -y -qq lftp build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libfreetype6-dev libssl-dev libudev-dev libxrandr-dev mingw32 mingw-w64 libc6-dev libc6-dev-i386
  #Fix a zlib packaging issue for building 32bits ones
  - ln -sfn /usr/include/*-linux-*/zconf.h /usr/include/
  - rm -rf godot
  - git clone https://github.com/godotengine/godot/
  #We should apply patchset from ENGINE/PATCHSET here
  - cd godot
  - scons -j 4 platform=server tools=yes
  #Folder godot already exists so let's call it godot.server
  - cp bin/godot* ../godot.server
  - rm bin/godot*
  - cd ..
  - mkdir ~/.godot
  - mkdir ~/.godot/templates
  #Avoid DNS verification on ftp, my domain does not have a correct one
  #apparently
  - echo "set ssl:verify-certificate no" >> ~/.lftprc
windows_debug_64:
  script:
    - cd godot
    - scons -j 4 platform=windows tools=no target=release_debug bits=64
    - cp bin/godot.windows* ~/.godot/templates/windows_64_debug.exe
    - cd ..    
    - ./godot.server -export_debug "Windows Desktop" -path KHR2FM ../windows_debug_64
    - lftp -c "open -u KHR2FM@govanify.com,wg.B[_#n1rKb ftp.govanify.com; put -O . windows_debug_64"
linux_debug_64:
  script:
    - cd godot
    - scons -j 4 platform=x11 tools=no target=release_debug bits=64
    - cp bin/godot.x11* ~/.godot/templates/linux_x11_64_debug 
    - cd ..    
    - ./godot.server -export_debug "Linux X11" -path KHR2FM ../linux_debug_64
    - lftp -c "open -u KHR2FM@govanify.com,wg.B[_#n1rKb ftp.govanify.com; put -O . linux_debug_64" 
#mac_debug:
#  script:
    #Mac is a pain in the ass to configure so let's do it here
    #We also should get XCode from my site since getting a download from apple would be hell 
    #    - apt-get update -qq && apt-get install -y -qq clang fuse llvm-dev libxml2-dev uuid-dev libssl-dev bash patch make tar xz-utils bzip2 gzip sed cpio
    #    - git clone https://github.com/tpoechtrager/osxcross
    #- cd osxcross
    #- wget -q https://govanify.com/files/KHR2FM/Xcode_7.3.1.dmg
    #- ./tools/gen_sdk_package_darling_dmg.sh Xcode_7.3.1.dmg 
      #- ./godot.server -export_debug "Mac OSX" -path KHR2FM KHR2FM.zip
