#TODO: Run once godot compilation then run export templates for each script and export
#      Godot compilation should be able to take patches from our repo!!

before_script:
  - mkdir KHR2FM
  - find * -maxdepth 0 -name 'KHR2FM' -prune -o -exec cp -vr '{}' ' KHR2FM' ';'
  - find * -maxdepth 0 -name 'KHR2FM' -prune -o -exec rm -rf '{}' ';'
  - apt-get update -qq && apt-get install -y -qq lftp build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libfreetype6-dev libssl-dev libudev-dev libxrandr-dev mingw32 mingw-w64
  - rm -rf godot
  - git clone https://github.com/godotengine/godot/
  #We should apply patchset from ENGINE/PATCHSET here
  - cd godot
  - scons platform=server tools=yes
  #Folder godot already exists so let's call it godot.server
  - cp bin/godot* ../godot.server
  - rm bin/godot*

  #Dear future self,
  #
  #You're looking at this file because
  #the parse function finally broke.
  #
  #It's not fixable. You have to rewrite it.
  #Sincerely, past self.
  #
  #Also it's probably at least
  #2017, did you ever take
  #that trip to Iceland?
  
  - num=`grep -n custom_binary/debug=\"\" export.cfg | head -1 | awk -F: '{ print $1}'`; sed -i "1,${num}s+custom_binary/debug=\"\"+custom_binary/debug=\"template.x32\"+" export.cfg
  - num=`grep -n custom_binary/debug=\"\" export.cfg | head -1 | awk -F: '{ print $1}'`; sed -i "1,${num}s+custom_binary/debug=\"\"+custom_binary/debug=\"template.exe\"+" export.cfg
  - num=`grep -n custom_package/debug=\"\" export.cfg | head -1 | awk -F: '{ print $1}'`; sed -i "1,${num}s+custom_package/debug=\"\"+custom_package/debug=\"template.apk\"+" export.cfg
- num=`grep -n custom_package/debug=\"\" export.cfg | head -2 | tail -1 | awk -F: '{ print $1}'`; sed -i "1,${num}s+custom_package/debug=\"\"+custom_package/debug=\"template.zip\"+" export.cfg
  - cd ..

windows_debug_32:
  script:
    - cd godot
    - scons platform=windows tools=no target=release_debug bits=32
    - cp bin/godot.windows* ../template.exe
    - cd ..    
    - ./godot.server -export "Windows Desktop" -path KHR2FM KHR2FM.exe
linux_debug_32:
  script:
    - cd godot
    - scons platform=x11 tools=no target=release_debug bits=32
    - cp bin/godot.x11* ../template.x32
    - cd ..    
    - ./godot.server -export "Linux X11" -path KHR2FM KHR2FM.x32
mac_debug:
  script:
    #Mac is a pain in the ass to configure so let's do it here
    #We also should get XCode from my site since getting a download from apple would be hell 
    - apt-get update -qq && apt-get install -y -qq clang llvm-dev libxml2-dev uuid-dev libssl-dev bash patch make tar xz-utils bzip2 gzip sed cpio
    - ./godot.server -export "Mac OSX" -path KHR2FM KHR2FM.zip
#An after script uploading the 3 files to the ftp KHR2FM@govanify.com password
#r,1x;#L=GrLF would be pretty cool to add
#HOWTO build KHR2FM with custom templates: search through export.cfg for the platform then next occurence of custom something and replace it by the templates path in made in the runner
#lftp ftp://KHR2FM:r,1x;#L=GrLF@govanify.com 
